#!/bin/sh
# sync-ui-kit.sh — materialize the pinned ui-agent-kit SDK zone into a Wails
# project's frontend/ (Go Agent Kit, Z13).
#
# The ui-kit/ zone is a pinned, verbatim mirror of the upstream ui-agent-kit
# sdk/ (see ui-kit/PIN.md). This tool copies it into a real Wails project:
#   - the whole zone       -> <frontend>/ui-kit/           (knowledge + code)
#   - code pieces          -> <frontend>/src/...            (per copy-rules.json)
#   - .pi/settings.json    -> wired with ["../ui-kit/skills"] (merge only)
#
# STRUCTURE EVOLUTION SAFETY (the "nothing gets destroyed" contract):
#   - Copy rules are NOT hardcoded: they come from ui-kit/copy-rules.json, a
#     local-owned file generated by the metaproject re-sync helper from the
#     upstream SDK's own cli/manifest.json at the pinned SHA. If upstream
#     renames a folder, adds a new code folder, or changes the layout, the
#     next re-sync regenerates the rules — this tool never needs a code
#     change, and it never copies a stale hardcoded path.
#   - Ownership manifest: <frontend>/ui-kit/.owned.json records every file
#     this tool wrote (path + sha256). On re-run:
#       * owned + unmodified files   -> refreshed from the zone;
#       * owned + unmodified, absent from the zone source -> deleted (clean
#         removal of SDK files upstream dropped — no zombie files);
#       * owned + MODIFIED by the consumer -> REFUSED (never clobber edits);
#       * existing unowned file at a destination path -> REFUSED (collision
#         with a consumer file).
#   - First run: existing files under the SDK-owned destination directories
#     are ADOPTED (recorded with their current sha256) and NOT overwritten;
#     only new files are copied. A second run then converges them to the
#     pinned zone version. Files outside the rule destinations are never
#     touched.
#   - Required shape: the zone must carry AGENTS.md, skills/ and ui-sdk/ —
#     if the pinned mirror lacks them (broken pin), the tool aborts before
#     copying anything.
#
# Wails detection (the "no trace" guarantee): the target must have wails.json
# AND a frontend/ directory with a package.json. Without both, the tool
# refuses with exit 1 and copies NOTHING — a non-Wails Go project never sees
# any SDK file.
#
# Usage:
#   bash tools/sync-ui-kit.sh                 # detect in the current dir
#   bash tools/sync-ui-kit.sh --target <dir>  # explicit project root
#   bash tools/sync-ui-kit.sh --dry-run       # print actions, change nothing
set -eu

# --- locate the kit root (this script lives in <kit>/tools/) ---------------
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
KIT_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
UI_KIT="$KIT_ROOT/ui-kit"
# Testability seam: UI_KIT_SRC overrides the zone source (used by the probe to
# simulate upstream evolutions without touching the real zone). Never set in
# production use.
if [ -n "${UI_KIT_SRC:-}" ]; then
	UI_KIT=$UI_KIT_SRC
fi

target=""
dry_run=0
while [ "$#" -gt 0 ]; do
	case "$1" in
	--target)
		target=$2
		shift 2
		;;
	--dry-run)
		dry_run=1
		shift
		;;
	*)
		echo "sync-ui-kit: unknown argument: $1" >&2
		exit 2
		;;
	esac
done

if [ -z "$target" ]; then
	target=$(pwd)
fi
target=$(CDPATH= cd -- "$target" 2>/dev/null && pwd) || {
	echo "sync-ui-kit: cannot resolve target: $target" >&2
	exit 2
}

# --- Wails detection --------------------------------------------------------
if [ ! -f "$target/wails.json" ]; then
	echo "sync-ui-kit: no wails.json in $target — not a Wails project; nothing copied (exit 1)." >&2
	exit 1
fi
frontend="$target/frontend"
if [ ! -f "$frontend/package.json" ]; then
	echo "sync-ui-kit: no frontend/package.json in $target — Wails frontend missing; nothing copied (exit 1)." >&2
	exit 1
fi

# --- required-shape check on the zone (structure evolution tripwire) -------
for required in AGENTS.md skills ui-sdk; do
	if [ ! -e "$UI_KIT/$required" ]; then
		echo "sync-ui-kit: ABORT — the ui-kit zone is missing '$required' (broken pin or upstream restructured sdk/); nothing copied." >&2
		exit 1
	fi
done

pin=$(grep -m1 '^| Pinned commit (SHA)' "$UI_KIT/PIN.md" 2>/dev/null | sed -E 's/.*`([0-9a-f]{7,})`.*/\1/')
[ -n "$pin" ] || pin="unknown"

echo "sync-ui-kit: Wails frontend detected at $frontend (pinned $pin)"
echo "sync-ui-kit: copying SDK from $UI_KIT"

# --- ownership manifest -----------------------------------------------------
MANIFEST="$frontend/ui-kit/.owned.json"
load_manifest() {
	if [ -f "$MANIFEST" ]; then
		python3 - "$MANIFEST" <<'PY' 2>/dev/null || echo "{}"
import json, sys
try:
    with open(sys.argv[1], encoding="utf-8") as f:
        data = json.load(f)
except Exception:
    print("{}")
    raise SystemExit
files = data.get("files", {})
print(json.dumps(files))
PY
	else
		echo "{}"
	fi
}

# We implement ownership decisions with python3 (JSON + sha256 in one place).

python3 - "$UI_KIT" "$frontend" "$pin" "$dry_run" <<'PY'
import hashlib
import json
import os
import sys

ui_kit, frontend, pin, dry_run = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4] == "1"
manifest_path = os.path.join(frontend, "ui-kit", ".owned.json")

def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

# previous ownership (frontend-relative path -> sha256)
owned = {}
if os.path.exists(manifest_path):
    try:
        with open(manifest_path, encoding="utf-8") as f:
            owned = json.load(f).get("files", {})
    except Exception:
        owned = {}

# copy rules: [ {src, dst} ] — src relative to ui-kit/, dst relative to frontend
rules_path = os.path.join(ui_kit, "copy-rules.json")
if os.path.exists(rules_path):
    with open(rules_path, encoding="utf-8") as f:
        rules = json.load(f)
    if not isinstance(rules, list):
        print("sync-ui-kit: ERROR copy-rules.json must be a list of {src,dst}", file=sys.stderr)
        sys.exit(1)
else:
    # fallback defaults (zones pinned before copy-rules.json existed)
    print("sync-ui-kit: warning: copy-rules.json missing in the zone - using built-in defaults", file=sys.stderr)
    rules = [
        {"src": "ui-sdk/components", "dst": "src/components"},
        {"src": "ui-sdk/blocks/blocks-so", "dst": "src/components"},
        {"src": "ui-sdk/examples/preferences-screen", "dst": "src/components/example"},
    ]

# the zone mirror itself is always copied (implicit rule)
rules = [{"src": ".", "dst": "ui-kit"}] + rules

# RESERVED: files the sync manages itself, never mirrored or deleted
reserved = {".owned.json", ".ui-agent-kit.json"}

def rel_files(root):
    out = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            full = os.path.join(dirpath, name)
            out.append(os.path.relpath(full, root))
    return out

# union map: every destination-relative path this zone produces -> absolute source
source_map = {}
for rule in rules:
    src_dir = ui_kit if rule["src"] == "." else os.path.join(ui_kit, rule["src"])
    if not os.path.isdir(src_dir):
        print(f"sync-ui-kit: ERROR copy rule source missing in the zone: {rule['src']} (stale copy-rules.json? re-run the metaproject re-sync)", file=sys.stderr)
        sys.exit(1)
    for rel in rel_files(src_dir):
        if os.path.basename(rel) in reserved:
            continue
        dst_rel = os.path.join(rule["dst"], rel)
        source_map.setdefault(dst_rel, os.path.join(src_dir, rel))

next_owned = {}
added = updated = removed = adopted = conflicts = 0

# copy/adopt/refresh pass (never clobbers consumer work)
for dst_rel, src_file in source_map.items():
    target = os.path.join(frontend, dst_rel)
    prev = owned.get(dst_rel)
    if os.path.exists(target):
        if prev is None:
            # unowned existing file: first run adopts (records, does NOT
            # overwrite); a later run treats it as owned+unmodified
            print(f"sync-ui-kit: adopt (no overwrite): {dst_rel}")
            adopted += 1
            next_owned[dst_rel] = sha256(target)
            continue
        if prev == "missing":
            # previous sync recorded the file but it vanished -> restore
            if dry_run:
                print(f"sync-ui-kit: [dry-run] restore {dst_rel}")
            else:
                os.makedirs(os.path.dirname(target), exist_ok=True)
                with open(src_file, "rb") as s, open(target, "wb") as d:
                    d.write(s.read())
            next_owned[dst_rel] = sha256(src_file)
            updated += 1
            continue
        if sha256(target) != prev:
            # consumer modified an SDK-owned file -> never clobber
            print(f"sync-ui-kit: REFUSED (modified by consumer, preserved): {dst_rel}", file=sys.stderr)
            conflicts += 1
            next_owned[dst_rel] = prev
            continue
        # owned + unmodified -> refresh
        if dry_run:
            print(f"sync-ui-kit: [dry-run] update {dst_rel}")
        else:
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with open(src_file, "rb") as s, open(target, "wb") as d:
                d.write(s.read())
        next_owned[dst_rel] = sha256(src_file)
        updated += 1
    else:
        # new file
        if dry_run:
            print(f"sync-ui-kit: [dry-run] add {dst_rel}")
        else:
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with open(src_file, "rb") as s, open(target, "wb") as d:
                d.write(s.read())
        next_owned[dst_rel] = sha256(src_file)
        added += 1

# single deletion pass: owned files no rule produces anymore (upstream removed
# them) — deleted ONLY when unmodified; consumer edits are preserved.
for dst_rel, prev in owned.items():
    if os.path.basename(dst_rel) in reserved:
        continue
    if dst_rel in source_map:
        continue
    target = os.path.join(frontend, dst_rel)
    if prev != "missing" and os.path.exists(target) and sha256(target) != prev:
        print(f"sync-ui-kit: REFUSED to delete (modified by consumer, preserved): {dst_rel}", file=sys.stderr)
        conflicts += 1
        next_owned[dst_rel] = prev
        continue
    if dry_run:
        print(f"sync-ui-kit: [dry-run] remove {dst_rel}")
    else:
        if os.path.exists(target):
            os.remove(target)
    removed += 1

# write the ownership manifest (only when actually syncing)
if dry_run:
    print(f"sync-ui-kit: [dry-run] write {manifest_path}")
else:
    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump({"schema": 1, "pin": pin, "files": next_owned}, f, indent=2, sort_keys=True)
        f.write("\n")

print(f"sync-ui-kit: +{added} added, {updated} refreshed, {removed} removed, {adopted} adopted, {conflicts} consumer-file conflict(s) preserved")
if conflicts:
    print(f"sync-ui-kit: FAILED — {conflicts} consumer-file conflict(s) preserved; resolve them (the manifest keeps them safe) and re-run.", file=sys.stderr)
    sys.exit(1)
PY

# --- wire .pi/settings.json (merge, never destructive) ----------------------
wire_skills() {
	if [ "$dry_run" = 1 ]; then
		echo "sync-ui-kit: [dry-run] wire ../ui-kit/skills into $frontend/.pi/settings.json"
		return 0
	fi
	mkdir -p "$frontend/.pi"
	settings="$frontend/.pi/settings.json"
	if [ ! -f "$settings" ]; then
		printf '{\n  "skills": ["../ui-kit/skills"]\n}\n' >"$settings"
		echo "sync-ui-kit: created $settings"
		return 0
	fi
	if grep -q 'ui-kit/skills' "$settings"; then
		echo "sync-ui-kit: $settings already declares the SDK skills"
		return 0
	fi
	if command -v python3 >/dev/null 2>&1; then
		python3 - "$settings" <<'PY'
import json, sys
path = sys.argv[1]
try:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
except Exception:
    import shutil
    shutil.copyfile(path, path + ".bak")
    data = {}
skills = data.get("skills")
if not isinstance(skills, list):
    skills = []
if "../ui-kit/skills" not in skills:
    skills.append("../ui-kit/skills")
data["skills"] = skills
with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
print(f"sync-ui-kit: wired ../ui-kit/skills into {path}")
PY
	else
		echo "sync-ui-kit: warning: $settings exists without the SDK skills and python3 is missing — add \"../ui-kit/skills\" to its \"skills\" array manually." >&2
	fi
}
wire_skills

# --- installed marker -------------------------------------------------------
if [ "$dry_run" = 1 ]; then
	echo "sync-ui-kit: [dry-run] write ui-kit/.ui-agent-kit.json"
else
	printf '{\n  "version": "%s",\n  "source": "goak-sync"\n}\n' "$pin" >"$frontend/ui-kit/.ui-agent-kit.json"
	echo "sync-ui-kit: wrote ui-kit/.ui-agent-kit.json (pinned $pin)"
fi

echo "sync-ui-kit: done. Read $frontend/ui-kit/AGENTS.md before UI work; UI skills are active when Pi runs inside $frontend."
