#!/usr/bin/env python3
"""structure.md — deterministic generator and drift checker (charter Layer 5.1).

Every project generated by the kit ships a `structure.md` at its root: a
reading map for a non-developer, not an inventory of files. The tree side of
that file must be verifiable against the real tree by a deterministic tool;
semantic content (roles, reading paths, explanations) is human enrichment and
is never claimed to be machine-verifiable (see KIT_CHARTER.md Layer 5.1).

This module provides both halves of the mechanism:

- `generate(project_dir)` derives the tree side from the actual tree
  (top-level directories, Go package names, entry points, test locations,
  internal/public boundary) and emits the structure.md skeleton with
  human-semantic sections left for review.
- `check(project_dir, text)` validates the machine-checked "Tree facts"
  block of an existing structure.md (completeness + tree-side conformity)
  plus the entry-completeness of the roles section. It never validates
  prose.

Usage (CLI):
    python3 tools/generators/structure_md.py generate <project-dir>
    python3 tools/generators/structure_md.py check   <project-dir>

The product validator (validate-kitv2.py) imports this module and runs
`check` on every sourced template, so a drifted structure.md blocks the gate.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import TypedDict


class TreeFacts(TypedDict):
    top_dirs: list[str]
    packages: dict[str, str]
    entry_points: list[str]
    test_files: list[str]
    internal_boundary: str


def _go_files(directory: Path) -> list[Path]:
    return sorted(p for p in directory.glob("*.go") if p.is_file())


def _package_of(directory: Path) -> str | None:
    for path in _go_files(directory):
        text = path.read_text(encoding="utf-8", errors="replace")
        match = re.search(r"^package\s+(\w+)", text, re.MULTILINE)
        if match:
            return match.group(1)
    return None


def derive_tree_facts(project_dir: Path) -> TreeFacts:
    """Derive the machine-checkable tree side of a project."""
    root = Path(project_dir)
    top_dirs = sorted(
        entry.name
        for entry in root.iterdir()
        if entry.is_dir() and entry.name != ".git"
    )
    packages: dict[str, str] = {}
    for dirpath, dirnames, _ in os.walk(root):
        dirnames[:] = [name for name in dirnames if name != ".git"]
        depth = len(Path(dirpath).relative_to(root).parts)
        if depth > 3:
            continue
        package = _package_of(Path(dirpath))
        if package is not None:
            rel = "." if Path(dirpath) == root else str(Path(dirpath).relative_to(root))
            packages[rel] = package
    packages = {rel: packages[rel] for rel in sorted(packages)}
    entry_points = sorted(rel for rel, package in packages.items() if package == "main")
    test_files = sorted(
        str(p.relative_to(root)) for p in root.rglob("*_test.go") if p.is_file()
    )
    return {
        "top_dirs": top_dirs,
        "packages": packages,
        "entry_points": entry_points,
        "test_files": test_files,
        "internal_boundary": "present" if "internal" in top_dirs else "absent",
    }


def _format_list(items: list[str]) -> str:
    return "; ".join(items)


def _package_lines(packages: dict[str, str]) -> str:
    return "; ".join(
        f"{rel if rel != '.' else '(root)'} -> {pkg}" for rel, pkg in packages.items()
    )


def generate(project_dir: Path, title: str | None = None) -> str:
    """Emit the structure.md skeleton with the derived tree side."""
    facts = derive_tree_facts(Path(project_dir))
    heading = title or Path(project_dir).name
    roles: list[str] = []
    if "(root)" in {rel if rel != "." else "(root)" for rel in facts["packages"]}:
        root_pkg = facts["packages"]["."]
        roles.append(f"- (root) — `{root_pkg}` package: <!-- role -->")
    for name in facts["top_dirs"]:
        if name.startswith("."):
            continue
        roles.append(f"- `{name}/` — <!-- role -->")
    if any(name.startswith(".") for name in facts["top_dirs"]):
        roles.append(
            "- `.github/` and other dot-dirs — development tooling; not part of "
            "the application's reading path"
        )
    if not roles:
        roles.append(
            "- (flat layout) — no top-level directories; the package is the boundary"
        )
    return f"""# {heading} — reading map

This map explains how to navigate this project. The **Tree facts** section
below is machine-checked by the kit's drift gate (it cannot drift silently);
the role lines, reading path, and boundary explanations are human-reviewed
content and are not machine-verifiable by design.

## Tree facts (machine-checked; do not edit)

```text
top_dirs: {_format_list(facts["top_dirs"])}
packages: {_package_lines(facts["packages"])}
entry_points: {"; ".join("(root)" if p == "." else p for p in facts["entry_points"])}
test_files: {_format_list(facts["test_files"])}
internal_boundary: {facts["internal_boundary"]}
```

## Directory roles

{chr(10).join(roles)}

## Reading path

<!-- Describe one concrete behavior and walk it through the directories. -->

## Public vs internal boundary

<!-- What is private implementation, what is public API or entry point. -->

## Where the evidence lives

<!-- Tests and observable scenarios: list the test locations and how to run
them. The tree facts above enumerate every test file. -->
"""


def check(project_dir: Path, text: str) -> list[str]:
    """Verify the machine-checked parts of a structure.md. Returns defects."""
    facts = derive_tree_facts(Path(project_dir))
    defects: list[str] = []
    section = re.search(
        r"^## Tree facts \(machine-checked[^\n]*\)\n(.*?)(?=^## |\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if not section:
        return ["missing '## Tree facts (machine-checked)' section"]
    block = "\n".join(
        line
        for line in section.group(1).splitlines()
        if line.strip() and not line.lstrip().startswith("```")
    )
    values: dict[str, str] = {}
    for line in block.splitlines():
        key, separator, value = line.partition(":")
        if separator:
            values[key.strip()] = value.strip()

    def display_entry(point: str) -> str:
        return "(root)" if point == "." else point

    expected: dict[str, str] = {
        "top_dirs": "; ".join(facts["top_dirs"]),
        "packages": _package_lines(facts["packages"]),
        "entry_points": "; ".join(display_entry(p) for p in facts["entry_points"]),
        "test_files": "; ".join(facts["test_files"]),
        "internal_boundary": facts["internal_boundary"],
    }
    for key, want in expected.items():
        got = values.get(key, "<missing>")
        if got != want:
            defects.append(f"tree fact {key}: got {got!r}, tree has {want!r}")

    roles_section = re.search(
        r"^## Directory roles\n(.*?)(?=^## |\Z)", text, re.MULTILINE | re.DOTALL
    )
    if not roles_section:
        defects.append("missing '## Directory roles' section")
    else:
        role_text = roles_section.group(1)
        for name in facts["top_dirs"]:
            if name.startswith("."):
                continue
            if f"`{name}/`" not in role_text and f"`{name}`" not in role_text:
                defects.append(f"directory roles: no entry for `{name}/`")
        if "." in facts["packages"]:
            root_pkg = facts["packages"]["."]
            if f"`{root_pkg}`" not in role_text:
                defects.append(
                    f"directory roles: no entry mentioning the `{root_pkg}` package"
                )

    boundary_section = re.search(
        r"^## Public vs internal boundary\n(.*?)(?=^## |\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if not boundary_section:
        defects.append("missing '## Public vs internal boundary' section")
    elif facts[
        "internal_boundary"
    ] == "present" and "internal/" not in boundary_section.group(1):
        defects.append("boundary section does not mention the `internal/` boundary")

    evidence_section = re.search(
        r"^## Where the evidence lives\n(.*?)(?=^## |\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if not evidence_section:
        defects.append("missing '## Where the evidence lives' section")
    elif not any(path in evidence_section.group(1) for path in facts["test_files"]):
        defects.append(
            "evidence section references no real test file (tree facts list: "
            + ("; ".join(facts["test_files"]) or "none")
            + ")"
        )
    return defects


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    command, project = args[0], Path(args[1])
    if not project.is_dir():
        print(f"structure_md: not a directory: {project}", file=sys.stderr)
        return 2
    if command == "generate":
        print(generate(project), end="")
        return 0
    if command == "check":
        text = (project / "structure.md").read_text(encoding="utf-8")
        defects = check(project, text)
        if defects:
            print("structure.md defects:", file=sys.stderr)
            for defect in defects:
                print(f"  - {defect}", file=sys.stderr)
            return 1
        print(f"structure.md: PASS ({project})")
        return 0
    print(f"structure_md: unknown command {command!r}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
