// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcsqlite

import (
	"context"
)

const createFoo = `-- name: CreateFoo :execlastid
INSERT INTO foos (name) VALUES (?)
`

func (q *Queries) CreateFoo(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFoo, name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getFoo = `-- name: GetFoo :one
SELECT id, name, created_at FROM foos WHERE id = ?
`

func (q *Queries) GetFoo(ctx context.Context, id int64) (Foo, error) {
	row := q.db.QueryRowContext(ctx, getFoo, id)
	var i Foo
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listFoos = `-- name: ListFoos :many
SELECT id, name, created_at FROM foos ORDER BY id
`

func (q *Queries) ListFoos(ctx context.Context) ([]Foo, error) {
	rows, err := q.db.QueryContext(ctx, listFoos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foo
	for rows.Next() {
		var i Foo
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
